[build]

base = "/"

publish = "/dist/"

command = "parcel build index.html"

[[redirects]]
  from = "/viewchar"
  to = "/viewchar"
  status = "200"
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"

